""" agents/constants """

# Agents' parameters
PRICE_MIN, PRICE_MAX = 1, 100
BUDGET_MIN, BUDGET_MAX = 0, 100
QTY_MIN, QTY_MAX = 1, 100

# Buyers' parameters
BUDGET = 70
MEMORY_BUYER = 0.5
RISK_TOLERANCE_BUYER = 0.2
CURIOSITY_BUYER = 0.1
BANDIT_STEEPNESS_BUYER = 10
BANDIT_BREAKPOINT_BUYER = 0.5
MYOPIA_BUYER = 0.7
PENALTY_BUYER = 0.5

# Sellers' parameters
PRICE_PROD = 30
MEMORY_SELLER = 0.5
RISK_TOLERANCE_SELLER = 0.2
CURIOSITY_SELLER = 0.1
BANDIT_STEEPNESS_SELLER = 10
BANDIT_BREAKPOINT_SELLER = 0.5
